name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Get dependencies
      run: go mod download
    
    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        binary_name="tsplice-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          binary_name="${binary_name}.exe"
        fi
        go build -ldflags="-s -w" -o "$binary_name" .
        # Verify it's actually a binary
        file "$binary_name"
      id: build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tsplice-${{ matrix.goos }}-${{ matrix.goarch }}
        path: tsplice-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
    
    - name: Prepare release assets
      run: |
        mkdir -p release-assets
        find ./artifacts -type f -exec cp {} release-assets/ \;
        ls -lah release-assets/
        # Verify binaries
        for file in release-assets/*; do
          if [[ ! "$file" == *.exe ]]; then
            file "$file"
          fi
        done
    
    - name: Create Release
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "## Changes
        
        Release ${{ github.ref_name }} of tsplice.
        
        ## Downloads
        
        Choose the appropriate binary for your platform:
        
        - **Linux AMD64**: \`tsplice-${{ github.ref_name }}-linux-amd64\`
        - **Linux ARM64**: \`tsplice-${{ github.ref_name }}-linux-arm64\`
        - **macOS AMD64 (Intel)**: \`tsplice-${{ github.ref_name }}-darwin-amd64\`
        - **macOS ARM64 (Apple Silicon)**: \`tsplice-${{ github.ref_name }}-darwin-arm64\`
        - **Windows AMD64**: \`tsplice-${{ github.ref_name }}-windows-amd64.exe\`" \
          release-assets/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}